import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck, Webhook } from "lucide-react";

import { Container } from "@/components/layout/PageShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/admin/integrations")({head:()=>({meta:[{title:"Integration control centre | DOMUREVA"},{name:"description",content:"Monitor health, failures, replay-safe webhooks and manual-review queues across DOMUREVA integrations."},{property:"og:title",content:"Integration control centre | DOMUREVA"},{property:"og:description",content:"Health, last success, failures and retry queues for every DOMUREVA integration."}]}),component:IntegrationsPage});
const SYSTEMS=[{key:"leadlens",label:"LeadLens"},{key:"dokuvera",label:"Dokuvera"},{key:"gabley",label:"Gabley"},{key:"gabley_retrofit",label:"Gabley Retrofit"},{key:"craftvaro",label:"Craftvaro"},{key:"stripe",label:"Stripe"},{key:"resend",label:"Resend"}] as const;
type EventRow={id:string;provider:string;event_type:string;status:string;error:string|null;created_at:string};
function IntegrationsPage(){const qc=useQueryClient();const events=useQuery({queryKey:["admin","integration-events"],queryFn:async()=>{const {data,error}=await supabase.from("integration_events").select("id,provider,event_type,status,error,created_at").order("created_at",{ascending:false}).limit(200);if(error)throw error;return(data??[]) as EventRow[]}});const triggerSync=useMutation({mutationFn:async(integration:string)=>{const {data:{session}}=await supabase.auth.getSession();const res=await fetch("/api/integrations/sync",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify({integration,jobType:"sync"})});const body=await res.json();if(!res.ok)throw new Error(body?.error??"Sync failed");return body as {status:string;integration:string}},onSuccess:(d)=>{toast.success(`${d.integration} sync ${d.status}`);qc.invalidateQueries({queryKey:["admin","integration-events"]})},onError:(e:Error)=>toast.error("Could not queue sync",{description:e.message})});const summaries=SYSTEMS.map(s=>{const rows=(events.data??[]).filter(e=>e.provider===s.key);return{...s,last:rows[0],success:rows.find(e=>e.status==="processed"),failures:rows.filter(e=>e.status==="failed").length}});const totalFailures=summaries.reduce((a,x)=>a+x.failures,0);
return <Container className="max-w-[1240px]">
 <div className="overflow-hidden rounded-[30px] bg-navy p-7 text-navy-foreground shadow-lift md:p-9"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-leaf-soft">Platform operations</p><h1 className="mt-3 font-display text-3xl font-bold md:text-5xl">Integration control centre</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-navy-foreground/68">One operational view across discovery, evidence, retrofit, delivery, payments and communications.</p></div><Webhook className="size-9 text-leaf-soft"/></div></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-3">{[[CheckCircle2,"Systems monitored",SYSTEMS.length],[AlertTriangle,"Current failures",totalFailures],[ShieldCheck,"Trust model","Server-side"]].map(([Icon,l,v])=>{const I=Icon as typeof CheckCircle2;return <div key={String(l)} className="rounded-3xl border border-border bg-card p-5 shadow-card"><I className="size-5 text-accent"/><p className="mt-4 text-sm text-muted-foreground">{String(l)}</p><p className="mt-1 font-display text-3xl font-bold text-primary">{String(v)}</p></div>})}</div>
 <div className="mt-8">{events.isLoading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-44 rounded-3xl"/>)}</div>:events.isError?<Card className="rounded-3xl border-destructive/40"><CardContent className="flex items-center gap-2 p-6 text-sm text-destructive"><AlertTriangle className="size-4"/>Could not load integration events.</CardContent></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{summaries.map(s=><Card key={s.key} className="rounded-3xl shadow-card"><CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Integration</p><CardTitle className="mt-2 text-lg">{s.label}</CardTitle></div>{s.failures>0?<Badge variant="destructive">{s.failures} failing</Badge>:<Badge className="bg-success text-success-foreground">Healthy</Badge>}</CardHeader><CardContent className="space-y-3 text-xs text-muted-foreground"><p>Last event: {s.last?new Date(s.last.created_at).toLocaleString():"none recorded"}</p><p>Last success: {s.success?new Date(s.success.created_at).toLocaleString():"none recorded"}</p>{["leadlens","dokuvera","gabley","gabley_retrofit","craftvaro"].includes(s.key)?<Button size="sm" variant="outline" className="rounded-full gap-1" disabled={triggerSync.isPending} onClick={()=>triggerSync.mutate(s.key)}><RefreshCw className="size-3"/>Sync now</Button>:null}</CardContent></Card>)}</div>}</div>
 <Card className="mt-8 rounded-3xl shadow-card"><CardHeader><CardTitle>Recent integration events</CardTitle><CardDescription>Latest webhook and job activity across all providers.</CardDescription></CardHeader><CardContent>{events.data?.length?<ul className="divide-y divide-border">{events.data.slice(0,20).map(e=><li key={e.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-medium capitalize text-primary">{e.provider} · {e.event_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(e.created_at).toLocaleString()}</p>{e.error?<p className="mt-1 text-xs text-destructive">{e.error}</p>:null}</div><Badge variant={e.status==="failed"?"destructive":"secondary"}>{e.status}</Badge></li>)}</ul>:<div className="rounded-2xl border border-dashed border-border p-8 text-center"><Webhook className="mx-auto size-7 text-accent"/><p className="mt-3 text-sm text-muted-foreground">No integration events recorded yet.</p></div>}</CardContent></Card>
</Container>}
