export type PackSection={
  title:string;
  required:boolean;
  items:{label:string;status:'ready'|'missing'|'review';sourceUrl?:string;documentId?:string}[];
};

export function buildPackSpec(input:{
 caseId:string;
 propertyAddress:string;
 schemeTitle:string;
 eligibilitySummary:string;
 sections:PackSection[];
}){
 const complete=input.sections.every(s=>!s.required||s.items.every(i=>i.status==='ready'));
 return {
   title:`DOMUREVA Application Pack`,
   caseId:input.caseId,
   propertyAddress:input.propertyAddress,
   schemeTitle:input.schemeTitle,
   eligibilitySummary:input.eligibilitySummary,
   sections:input.sections,
   complete,
   footer:'Generated by DOMUREVA. Funding eligibility remains subject to the administering authority’s final decision.'
 };
}
